import Head from 'next/head'
import { getSortedPostsData } from '../../lib/posts';

export interface IHomeProps {
  id: string;
  date?: string;
  title?: string;
  contentHtml?: string;
}

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home({ allPostsData }: {allPostsData: IHomeProps[]}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <h2>Blog</h2>
          <br/>
          <ul>
            {allPostsData.map(({ id, date, title }) => (
              <li key={id}>
                {title}
                <br />
                {id}
                <br />
                {date}
                <hr/>
              </li>
            ))}
          </ul>
        </section>
      </main>
    </>
  )
}
